---

- name: Install apptainer (RedHat-family)
  when: ansible_os_family == 'RedHat'
  block:

    - name: Install apptainer
      ansible.builtin.package:
        name: "{{ apptainer_packages }}"
        state: present

- name: Install apptainer (Ubuntu)
  when: ansible_distribution == 'Ubuntu'
  vars:
    apptainer_apt_keyfile_tmp: "/tmp/{{ apptainer_apt_keyfile | basename }}"
  block:

    - name: Download the GPG key
      ansible.builtin.get_url:
        url: "{{ apptainer_apt_key }}"
        dest: "{{ apptainer_apt_keyfile_tmp }}"
        owner: root
        group: root
        mode: "0644"

    - name: Convert APT key into binary format
      ansible.builtin.command:
        cmd: >-
          gpg
          --batch
          --yes
          --no-tty
          --dearmor
          -o {{ apptainer_apt_keyfile }}
          {{ apptainer_apt_keyfile_tmp }}
      tags: molecule-idempotence-notest

    - name: Add official repository
      ansible.builtin.apt_repository:
        repo: >
          deb
          [arch=amd64,arm64 signed-by={{ apptainer_apt_keyfile }}]
          {{ apptainer_apt_url }}
          {{ ansible_distribution_release }}
          main
        filename: "apptainer"
        state: present
      register: _apt_repo

    - name: Update package list (APT)  # noqa no-handler
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0
      when: _apt_repo.changed

    - name: Install apptainer
      ansible.builtin.package:
        name: "{{ apptainer_packages }}"
        state: present
