---

- name: Install apptainer (RedHat-family)
  when: ansible_os_family == 'RedHat'
  block:

    - name: Install apptainer
      ansible.builtin.package:
        name: "{{ apptainer_packages }}"
        state: present

- name: Install apptainer (Ubuntu)
  when: ansible_distribution == 'Ubuntu'
  vars:
    apptainer_tmp1: "/tmp/{{ apptainer_apt_keyfile | basename }}1"
    apptainer_tmp2: "/tmp/{{ apptainer_apt_keyfile | basename }}2"
  block:

    - name: Download the GPG key
      ansible.builtin.get_url:
        url: "{{ apptainer_apt_key }}"
        dest: "{{ apptainer_tmp1 }}"
        owner: root
        group: root
        mode: "0644"
      tags: molecule-idempotence-notest

    - name: Convert APT key into binary format
      ansible.builtin.command:
        cmd: >-
          gpg --batch --yes --no-tty --dearmor -o {{ apptainer_tmp2 }} {{ apptainer_tmp1 }}
      changed_when: false

    - name: Update APT key
      ansible.builtin.copy:
        src: "{{ apptainer_tmp2 }}"
        dest: "{{ apptainer_apt_keyfile }}"
        mode: "0644"
        remote_src: true

    - name: Add official repository
      ansible.builtin.copy:
        content: >
          deb
          [arch=amd64,arm64 signed-by={{ apptainer_apt_keyfile }}]
          {{ apptainer_apt_url }}
          {{ ansible_distribution_release }}
          main
        dest: /etc/apt/sources.list.d/apptainer.list
        mode: "0644"
      register: _apt_repo

    - name: Delete temporary files
      ansible.builtin.file:
        path: "{{ apptainer_tmp2 }}"
        state: absent
      changed_when: false

    - name: Update package list (APT)  # noqa no-handler
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 0
      when: _apt_repo.changed

    - name: Install apptainer
      ansible.builtin.package:
        name: "{{ apptainer_packages }}"
        state: present
